spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432
    username: postgres
    password: admin
    name: webflux_poc
  flyway:
    url: jdbc:postgresql://localhost:5432/${spring.r2dbc.name}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
